services:
  web:
    container_name: inscribe-web
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - NODE_VERSION=22.1.0
        - PROJECT=web
        - PORT=3000
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL=${NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
  api:
    container_name: inscribe-api
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - NODE_VERSION=22.1.0
        - PROJECT=api
        - PORT=3333
    ports:
      - "3333:3333"
    env_file:
      - .env.prod
    depends_on:
      - nats-server
  nats-server:
    image: nats:latest
    container_name: inscribe-nats-server
    ports:
      - "4222:4222"  
      - "8222:8222"  
      - "6222:6222" 
    environment:
      - NATS_SERVER_NAME=nats-server
    command: >
      -V 
      -m 8222  
    volumes:
      - nats_data:/nats_data  
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
volumes:
  nats_data: