services:
  web:
    container_name: inscribe-web
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - NODE_VERSION=22.1.0
        - PROJECT=web
        - PORT=3000
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL=${NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
  api:
    container_name: inscribe-api
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - NODE_VERSION=22.1.0
        - PROJECT=api
        - PORT=3333
    ports:
      - "3333:3333"
    env_file:
      - .env.prod
    depends_on:
      - nats-server
  nats-server:
    image: nats:latest
    container_name: inscribe-nats-server
    ports:
      - "4222:4222"  
      - "8222:8222"  
      - "6222:6222" 
    environment:
      - NATS_SERVER_NAME=nats-server
    command: >
      -V 
      -m 8222  
    volumes:
      - nats_data:/nats_data  
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # otel-collector:
  #   image: otel/opentelemetry-collector:0.67.0
  #   restart: always
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - type: bind
  #       source: ./otel-collector-config.yaml
  #       target: /etc/otel-collector-config.yaml
  #       read_only: true
  #   ports:
  #     - "1888:1888"   # pprof extension
  #     - "8888:8888"   # Prometheus metrics exposed by the collector
  #     - "8889:8889"   # Prometheus exporter metrics
  #     - "13133:13133" # health_check extension
  #     - "4317:4317"   # OTLP gRPC receiver
  #     - "4318:4318"   # OTLP HTTP receiver
  #     - "55679:55679" # zpages extension
  #   depends_on:
  #     - jaeger-all-in-one
volumes:
  nats_data: