import {createEnv} from '@t3-oss/env-nextjs';
import {z}  from 'zod'

export const uiEnv = createEnv({
  client: {
    NEXT_PUBLIC_API_URL: z.string().url(),
    NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL: z.string().url(),
  },
  runtimeEnv: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL: process.env.NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL,
  },
  emptyStringAsUndefined: true,
})

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'production']).default('development'),
    SERVER_PORT: z.coerce.number().default(3333),
    RESEND_API_KEY: z.string(),
    DATABASE_URL: z.string(),
    JWT_SECRET: z.string(),
    LANGCHAIN_PROJECT: z.string(),
    LANGCHAIN_CALLBACKS_BACKGROUND: z.coerce.boolean().default(true),
    LANGCHAIN_TRACING_V2: z.coerce.boolean().default(true),
    LANGCHAIN_API_KEY: z.string(),
    OPENAI_API_KEY: z.string(),
    NATS_SERVER_URL: z.string(),
    NATS_YOUTUBE_TOPIC: z.string(),
    STRIPE_SECRET_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),
    AUTH_REDIRECT_URL: z.string(),
    PROXY_CONFIG_1: z.string(),
    PROXY_CONFIG_2: z.string(),
    PROXY_CONFIG_3: z.string(),
    PROXY_CONFIG_4: z.string(),
    PROXY_CONFIG_5: z.string(),
    PROXY_AUTH: z.string(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    LANGCHAIN_CALLBACKS_BACKGROUND: process.env.LANGCHAIN_CALLBACKS_BACKGROUND,
    SERVER_PORT: process.env.SERVER_PORT,
    NODE_ENV: process.env.NODE_ENV,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    LANGCHAIN_PROJECT: process.env.LANGCHAIN_PROJECT,
    LANGCHAIN_TRACING_V2: process.env.LANGCHAIN_TRACING_V2,
    LANGCHAIN_API_KEY: process.env.LANGCHAIN_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    NATS_SERVER_URL: process.env.NATS_SERVER_URL,
    NATS_YOUTUBE_TOPIC: process.env.NATS_YOUTUBE_TOPIC,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    AUTH_REDIRECT_URL: process.env.AUTH_REDIRECT_URL,
    PROXY_CONFIG_1: process.env.PROXY_CONFIG_1,
    PROXY_CONFIG_2: process.env.PROXY_CONFIG_2,
    PROXY_CONFIG_3: process.env.PROXY_CONFIG_3,
    PROXY_CONFIG_4: process.env.PROXY_CONFIG_4,
    PROXY_CONFIG_5: process.env.PROXY_CONFIG_5,
    PROXY_AUTH: process.env.PROXY_AUTH,
  },
  emptyStringAsUndefined: true,
  skipValidation: true,
});